-- AlterTable
ALTER TABLE `SheetSticker` MODIFY `x` INTEGER NOT NULL DEFAULT 0,
    MODIFY `y` INTEGER NOT NULL DEFAULT 0,
    MODIFY `rotation` DOUBLE NOT NULL DEFAULT 0.0,
    MODIFY `scaleX` DOUBLE NOT NULL DEFAULT 0.0,
    MODIFY `scaleY` DOUBLE NOT NULL DEFAULT 0.0,
    MODIFY `stickerBorderWidth` DOUBLE NULL;
